### PR TITLE
# 2023-5-24 sync RetroBat menu to v5.3 base

### PR DESCRIPTION
**Pull request by bilu-git**

### CODE REVIEW

**Comment by davidrenne** [comment]
@bilu-git @virtual-man007 what finally happened to the forums going away?  It sucks...

**Comment by Mustang98503** [comment]
I'm more the extremely sad vman was and always we be the best...

**Comment by RichPlace4** [comment]
Any news?

**Comment by bilu-git** [comment]
> Any news?

https://www.twitch.tv/retro_bliss

**Comment by davidrenne** [comment]
@RichPlace4 email me from my github and say hello.

**Pull request merged**
